package core;

public enum AppEventType {
    ALL_INSTRUMENTS, INSTRUMENT,
    OPEN_POSITIONS, CLOSED_POSITIONS,
    ALL_ORDERS,
    MARKET_ORDER,
    CASH, META,
    CREATE_ACCOUNT, DELETE_ACCOUNT
}
